(Changed) [PXN-5161] - Adapting PANView for receiving an issuer image in split cases *WIP*
mercadolibre/meli-card-drawer-ios pull request #116
Opened 2022-09-27 15:22 UTC by ignaciososaml

## What have changed?
We added a container in the PANView for the incoming issuer image from split cases. If the case is not split, we'll not show that container.

## How to test:

## Prints for layout changes:

## Extras:

2022-09-27 18:21 UTC, mvarani requested changes
Te dejé un comment para que mejoremos, y como es 100% visual y pasamos a una stackView (y para asegurarnos que no rompamos nada 😛) estaría bueno ver también:
- Que se vea igual que antes al no settear ninguna URL.
- Cómo se vería descargando correctamente la imagen.
- Cómo se vería si falla la descarga de la imagen.
- Cómo se vería si se settea un asset muy grande. De qué forma lo escala?

2022-09-27 18:21 UTC, mvarani commented on Source/Classes/View/PAN/PANView.swift
> +
Creo que usar esta función puede traer algunos problemas: 
- no está guardando en cache lo que descarga, así que va a hacer la descarga siempre que se pida el asset.
- por más que llegue la data, la creación de la UIImage puede dar nil (y crashear la app cuando intente settearla).

Qué te parece si rearmamos esto usando el método _getRemoteImage_ que está en el repo? Podés ver implementaciones de ejemplo que usamos para descargar y settear los assets en las cards.

2022-09-27 18:24 UTC, mvarani commented on Source/Classes/View/PAN/PANView.swift
> +    }
Creo que usar esta función puede traer algunos problemas:
- no está guardando en cache lo que descarga, así que va a hacer la descarga siempre que se pida el asset.
- por más que llegue la data, la creación de la UIImage puede dar nil (y crashear la app cuando intente settearla).

Qué te parece si rearmamos esto usando el método **getRemoteImage** que está en el repo? Podés ver implementaciones de ejemplo que usamos para descargar y settear los assets en las cards.

2022-09-28 15:09 UTC, GiselaARamosC requested changes

2022-09-28 15:09 UTC, GiselaARamosC commented on Source/Classes/View/PAN/PANView.swift
> +
Esto es mejor directamente hacer una lazy como hiciste con la stackView

2022-09-28 15:09 UTC, GiselaARamosC commented on Source/Classes/View/PAN/PANView.swift
> +        PANIssuerContainer.translatesAutoresizingMaskIntoConstraints = false
Esta property iria dentro de la lazy var que mencione anteriormente

2022-09-28 15:09 UTC, GiselaARamosC commented on Source/Classes/View/PAN/PANView.swift
> +        DispatchQueue.global().async {
Por que global() ?

2022-09-28 15:12 UTC, GiselaARamosC requested changes

2022-09-28 15:12 UTC, GiselaARamosC commented on Source/Classes/View/PAN/PANView.swift
> +                setIssuerImage(issuerImage)
Por seguridad, agregaria PANIssuerContainer.isHidden = false

2022-09-30 15:48 UTC, mvarani commented on Source/Classes/View/PAN/PANView.swift
> +    public func setPANStyle(_ cardUI: CardUI,_ customPAN: CustomPAN ,  _ disabled: Bool = false) {
La firma de esto no debería cambiar- y agregar parámetros obligatorios rompe las implementaciones ya puestas. Siempre hay que referirse al modelo de datos, y los cambios son sobre esta misma instancia de la vista (no a una nueva)

2022-09-30 15:48 UTC, mvarani commented on Source/Classes/View/PAN/PANView.swift
> +        }
Esto creo que no debería hacer falta. Siempre vamos a settear con URL, no enviando la imagen

2022-10-05 13:46 UTC, mvarani requested changes

2022-10-05 13:46 UTC, mvarani commented on Source/Classes/View/PAN/PANView.swift
> +    var customPAN: CustomPAN?
Esta property no va acá porque nunca va a tener valor ni se inicializa. Además tampoco tiene sentido porque es el objeto con el que se comunica quien integra carddrawer, no la vista. Fijate porfa de entender bien cómo funciona el CardUI

2022-10-05 13:46 UTC, mvarani commented on Source/Classes/View/PAN/PANView.swift
> +        if let imageURL = customPAN?.issuerImage as? String, !imageURL.isEmpty {
Mismo que arriba. CustomPAN no tiene ni va a tener valor acá

2022-10-05 13:46 UTC, mvarani commented on Source/Classes/View/PAN/PANView.swift
> +        PANLabel.translatesAutoresizingMaskIntoConstraints = false
Esta línea está repetida abajo

2022-10-05 13:46 UTC, mvarani commented on Source/Classes/View/PAN/PANView.swift
> +        PANContainer.translatesAutoresizingMaskIntoConstraints = false
Esta línea está repetida abajo x2

2022-10-05 13:46 UTC, mvarani commented on Source/Classes/View/PAN/PANView.swift
> +        configureStackView()
sigamos la lógica semántica de los otros métodos

2022-10-05 13:46 UTC, mvarani commented on Source/Classes/View/PAN/PANView.swift
> +            PANIssuerContainer.isHidden = true
Estos settings tendría que hacerlos el callback de cuando recibimos la imagen me parece, no solo por la existencia de la url

2022-10-05 13:49 UTC, mvarani commented on Source/Classes/View/PAN/PANView.swift
> +    private lazy var containerStackView: UIStackView = {
No me hace sentido el nombre de esta vista, y la pondría más arriba con las demás.

También: es necesario tener un container Y una stackView en ese container? La idea no era que la stackview lo reemplace? Por qué necesitaríamos los 2?

2022-10-06 15:44 UTC, lucschmidt commented on Source/Classes/View/PAN/PANView.swift
> +        if let imageURL = customPAN?.issuerImage as? String, !imageURL.isEmpty {
Lo mismo digo... No tendrá ningún valor en customPAN

2022-10-10 14:55 UTC, lucschmidt commented
Nacho, he estado revisando tu PR, tengo una gran duda sobre cómo estás haciendo las pruebas.
¿Puedes hacer algún mock simulando los cambios en cuestión?
Creo que muchos de los puntos cuestionados aquí podrían minimizarse presentando las pruebas adecuadas. ¿Lo has conseguido?

2022-10-11 21:17 UTC, ignaciososaml commented on Source/Classes/View/PAN/PANView.swift
> +    private lazy var containerStackView: UIStackView = {
Por el momento no he logrado asignar al containerStackView como único container ya que tengo conflictos de constraints, una vez que podamos realizar todas las pruebas intentaré realizar este cambio para que no tengamos que tener un container adicional

2022-10-11 21:18 UTC, ignaciososaml commented on Source/Classes/View/PAN/PANView.swift
> +                PANIssuerContainer.image = UIImage.placeholderImage(fromColor: .darkGray)
Imagino que esta asignación de valor a la image del PANIssuerContainer no corresponde según los lineamentos de UX pero es un ejemplo para mostrar una imagen en caso de obtener una URL que no descargue ninguna imagen

2022-10-12 14:57 UTC, GiselaARamosC requested changes

2022-10-12 14:57 UTC, GiselaARamosC commented on Source/Classes/Protocols/CardUI.swift
> +    public var issuerImage: String?
Es un nombre o una imagen? El nombre de la variable no es descriptivo

2022-10-12 14:57 UTC, GiselaARamosC commented on Source/Classes/View/PAN/PANView.swift
>      var cardUI: CardUI?
Esto tambien deberia ser private

2022-10-12 14:57 UTC, GiselaARamosC commented on Source/Classes/View/PAN/PANView.swift
> +
Todas las subviews deberian estar declarados arriba de todo

2022-10-12 14:57 UTC, GiselaARamosC commented on Source/Classes/Utils/UIImage+Gray.swift
> +
Cual es la idea de este metodo?

2022-10-12 14:57 UTC, GiselaARamosC commented on Source/Classes/View/PAN/PANView.swift
> +            if let imageURL = panStyle?.issuerImage as? String, !imageURL.isEmpty {
issuerImage ya es un string, por que castearlo de nuevo a String?

2022-10-12 14:57 UTC, GiselaARamosC commented on Source/Classes/View/PAN/PANView.swift
> +                PANIssuerContainer.image = UIImage.placeholderImage(fromColor: .darkGray)
En el caso de solo  probar o no etsar seguro, se deberia dejar el cambio de manera local o dejar comentado un TODO para saber que no es el resultado final

2022-10-12 14:57 UTC, GiselaARamosC commented on Source/Classes/View/PAN/PANView.swift
> +                PANIssuerContainer.isHidden = false
Aca estas repitiendo codigo, dentro del if y del else tenes lo mismo:

self.containerStackView.insertArrangedSubview(self.PANIssuerContainer, at: 0)
self.PANIssuerContainer.isHidden = false

Aun asi, siempre estarias agregando la view, y si no se necesita agregarla?

2022-10-12 18:56 UTC, ignaciososaml commented on Source/Classes/Utils/UIImage+Gray.swift
> +
La idea de este método era dejar una img de placeholder en caso de descarga fallida de la imagen del ícono. Voy a proceder a quitarla y quedo atento para saber como puedo dejar seteada una imagen de aspecto vacío para cuando no sea posible la descarga de la imagen

2022-10-12 19:22 UTC, ignaciososaml commented on Source/Classes/View/PAN/PANView.swift
>      var cardUI: CardUI?
si implemento `private var cardUI` rompe en el armado de las front views de las cartas por ser una depen, procedo a darle private a los atributos que corresponden a la PANView

2022-10-13 14:23 UTC, GiselaARamosC requested changes

2022-10-13 14:23 UTC, GiselaARamosC commented on Source/Classes/Protocols/CardUI.swift
> +    public var panIconImage: String?
Tampoco es descriptivo: si declaro una variable con nombre  `myStackview` y digo que es de tipo String, tiene sentido? `issuerImageUrl` puede ser un ejemplo de un nombre mas descriptivo, una url puede ser un string

2022-10-13 14:23 UTC, GiselaARamosC commented on Source/Classes/View/PAN/PANView.swift
> +    }()
subview declarada arriba de todo

2022-10-13 14:23 UTC, GiselaARamosC commented on Source/Classes/View/PAN/PANView.swift
> +    }
los inits deben estar declarados luego de las variables. El orden debe ser subviews, variables. enums, etc e inits

2022-10-13 14:23 UTC, GiselaARamosC commented on Source/Classes/View/PAN/PANView.swift
> +                        self.containerStackView.insertArrangedSubview(self.PANIconImageContainer, at: 0)
Es realmente necesario especificar la posicion en la que se quiere agregar la imagen? Si los componentes estuvieran seteados en el orden correcto, esto no seria necesario

2022-10-13 14:24 UTC, GiselaARamosC commented on Source/Classes/Utils/UIImage+Gray.swift
> +
Cual es la imagen en cuestion? Cual seria la necesidad de enviar un color?

2022-10-14 18:43 UTC, GiselaARamosC commented on Source/Classes/View/PAN/PANView.swift
> +                        self.containerStackView.insertArrangedSubview(self.PANIconImageContainer, at: 0)
Para que se respete, lo ideal es primero preguntar por la imagen y si corresponde, agregarla y luego hacer lo mismo con el numero y ponerlo en el init de la stackView

2022-10-17 15:16 UTC, GiselaARamosC requested changes

2022-10-18 19:14 UTC, mvarani commented on Source/Classes/View/PAN/PANView.swift
> +                PANLabel.removeFromSuperview()
esto rompe todas las implementaciones 😕 Que no le demos un mensaje como parte de estilo no significa que no tenga texto el label. El mensaje en panStyle es para sobreescribir lo que ya haya.

2022-10-18 19:21 UTC, mvarani reviewed
Sigo sin ver que funque nacho ☹️. Sin cambiar nada y compilando la testapp se ve esto (comparo vs. la feature branch sin este PR):

| Ahora | Antes |
|:-:|:-:|
| ![Ahora](https://user-images.githubusercontent.com/61248081/196523492-27139866-e3cb-4442-8786-eda01c0e770d.mp4)| ![Antes](https://user-images.githubusercontent.com/61248081/196523941-dc5a1d99-bfac-4915-a1de-1749f1379ccb.mp4)|

2022-10-21 14:17 UTC, mvarani commented on Source/Classes/Utils/UIImage+Gray.swift
> +        return newImage!
Force unwrappear prácticamente nunca es la solución ni es correcto. Esto me crasheó la app bastante rápido:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/61248081/197213787-e27f6b1c-25a4-4ee4-82a5-a48ad84e1848.png">

2022-10-21 14:17 UTC, mvarani commented on Source/Classes/View/PAN/PANView.swift
> +                PANLabel.isHidden = true
mismo comment que antes: _esto rompe todas las implementaciones creo 😕 Que no le demos un mensaje como parte de estilo no significa que no tenga texto el label. El mensaje en panStyle es para sobreescribir lo que ya haya._

2022-10-26 20:39 UTC, closed without merging